DROP TABLE IF EXISTS account CASCADE;
CREATE TABLE IF NOT EXISTS account
(
    id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    name  VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    roles VARCHAR(255)
);

DROP TABLE IF EXISTS resource CASCADE;
CREATE TABLE IF NOT EXISTS resource
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identifier VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    access BOOLEAN DEFAULT FALSE,
    category VARCHAR(10) DEFAULT 'FIGURE',
    type VARCHAR(10) DEFAULT 'VIDEO',
    account_id UUID REFERENCES account (id),
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);